have_fun: false

ignore_patterns:
  - "**/node_modules/**"
  - "dist/**"
  - "*.log"

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 10
  pull_request_opened:
    help: false
    summary: true
    code_review: true